name: Steffen jensen portfolio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8844
title: Steffen jensen portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9a8d7d'
    - '#bbb3a8'
    - '#d4d8e1'
    - '#544b46'
    - '#19110f'
  brandStrength: 0.9121191536542028
  lightness: 0.41407958907075226
  saturation: 0.07293348223902285
  rhythmicContrast: 0.8931403018068522
purpose: []
