name: Steffen jensen
favicon: null
layout_spectrum: 0.22871
typography_spectrum: 0.8844
title: Steffen jensen portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001020'
    - '#0b3043'
    - '#1f4751'
    - '#2a5a68'
    - '#456c7b'
  brandStrength: 0.9121191536542028
  lightness: 0.41407958907075226
  saturation: 0.07293348223902285
  rhythmicContrast: 0.8931403018068522
purpose: []
